language: java
sudo: required
install: mvn clean install

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - javadoc -private -sourcepath src main.java.game
