language: java
sudo: required
install: mvn install
jdk:
  - oraclejdk8
  
script: 
- mvn -f risk/pom.xml test
- "mvn -f risk/pom.xml cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
