language: java
sudo: required
install: mvn clean install

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - javadoc -sourcepath src/main/java/game src.main.java.game
#  - javadoc -private -sourcepath "src/main/java:src/main/ressources:src/test/java" -d /Users/pyrrha/IdeaProjects/aidons-les-fermiers/doc  marche.traitement.produits marche.traitement.marche marche.traitement.label marche.traitement.production marche.traitement.participant marche.traitement.exceptions
